const ADD_BRAND = 'GET_BRAND'
const ADD_MODEL = 'GET_MODEL'
const ADD_FUEL = 'GET_FUEL'
const BRAND_SELECT = 'BRAND_SELECT'
const MODEL_SELECT = 'MODEL_SELECT'
const FUEL_SELECT = 'FUEL_SELECT'
export default {
    ADD_BRAND,
    ADD_MODEL,
    ADD_FUEL,
    BRAND_SELECT,
    MODEL_SELECT,
    FUEL_SELECT
}